// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Glendon Chin
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// A copy is included at /LICENSE in the repository root.

import Foundation
import SwiftUI

extension NookTokenRegistry {
    /// The chrome metrics, in `NookChromeMetrics` declaration order.
    static let metricTokens: [NookDimensionToken] = [
        NookDimensionToken(.edgePadding, .component, .spacing, .token(.spaceMD), .length),
        NookDimensionToken(.expandedColumnSpacing, .component, .spacing, .token(.spaceMD), .length),
        NookDimensionToken(.topBarHeight, .component, .none, .points(Double(NookLayout.topBarHeight)), .length),
        NookDimensionToken(.topBarItemSpacing, .component, .spacing, .token(.spaceMD), .length),
        NookDimensionToken(.leadingClusterSpacing, .component, .spacing, .token(.spaceSM), .length),
        NookDimensionToken(.trailingClusterSpacing, .component, .spacing, .token(.spaceXS), .length),
        NookDimensionToken(
            .breadcrumbMaxWidth,
            .component,
            .none,
            .points(Double(NookLayout.breadcrumbMaxWidth)),
            .length
        ),
        NookDimensionToken(.headerIconSize, .component, .none, .points(24), .length),
        NookDimensionToken(.headerIconCornerRadius, .component, .radius, .points(7), .length),
        NookDimensionToken(.headerIconStrokeWidth, .component, .none, .points(1), .length),
        NookDimensionToken(.headerIconHoverLabelOpacity, .component, .none, .points(0.92), .opacity),
        NookDimensionToken(.brandMarkSize, .component, .type, .token(.typeSizeMD), .length),
        NookDimensionToken(.brandMarkStrokeWidth, .component, .none, .points(1.1), .length),
        NookDimensionToken(.brandMarkOpacity, .component, .none, .points(0.92), .opacity),
        NookDimensionToken(.compactSlotSize, .component, .none, .points(Double(NookLayout.compactSlotSize)), .length),
        NookDimensionToken(.compactLeadingGlyphOpacity, .component, .none, .points(0.88), .opacity),
        NookDimensionToken(.compactTrailingMarkSize, .component, .none, .points(20), .length),
        NookDimensionToken(.compactTrailingMarkStrokeWidth, .component, .none, .points(1.1), .length),
        NookDimensionToken(.compactTrailingMarkOpacity, .component, .none, .points(0.82), .opacity),
        NookDimensionToken(.bannerRowSpacing, .component, .spacing, .token(.spaceMD), .length),
        NookDimensionToken(.bannerCornerRadius, .component, .radius, .token(.radiusMD), .length),
        NookDimensionToken(.bannerContentHorizontalPadding, .component, .spacing, .token(.spaceLG), .length),
        NookDimensionToken(.bannerContentVerticalPadding, .component, .spacing, .points(7), .length),
        NookDimensionToken(.bannerSeverityGlyphTopInset, .component, .none, .points(1), .length),
        NookDimensionToken(.bannerDismissButtonSize, .component, .none, .points(18), .length),
        NookDimensionToken(.bannerMessageLabelOpacity, .component, .none, .points(0.92), .opacity),
        NookDimensionToken(.bannerStrokeOpacity, .component, .none, .points(0.65), .opacity),
        NookDimensionToken(.bannerStrokeWidth, .component, .none, .points(0.5), .length),
        NookDimensionToken(.shelfContentSpacing, .component, .spacing, .token(.spaceMD), .length),
        NookDimensionToken(.shelfRootVerticalPadding, .component, .spacing, .token(.spaceSM), .length),
        NookDimensionToken(.shelfDropZoneVerticalPadding, .component, .spacing, .points(28), .length),
        NookDimensionToken(.shelfDropZoneCornerRadius, .component, .radius, .token(.radiusLG), .length),
        NookDimensionToken(.shelfDropZoneStrokeWidth, .component, .none, .points(1), .length),
        NookDimensionToken(.shelfHeaderSpacing, .component, .spacing, .token(.spaceLG), .length),
        NookDimensionToken(.shelfChipSpacing, .component, .spacing, .token(.spaceXS), .length),
        NookDimensionToken(.shelfChipWidth, .component, .none, .points(72), .length),
        NookDimensionToken(.shelfChipPadding, .component, .spacing, .token(.spaceMD), .length),
        NookDimensionToken(.shelfChipCornerRadius, .component, .radius, .token(.radiusMD), .length),
        NookDimensionToken(.shelfIconSize, .component, .none, .points(34), .length),
        NookDimensionToken(.shelfRowVerticalPadding, .component, .spacing, .token(.spaceXXS), .length),
        NookDimensionToken(.activityCardSpacing, .component, .spacing, .token(.spaceXL), .length),
        NookDimensionToken(.activityIconWidth, .component, .none, .points(30), .length),
        NookDimensionToken(.activityTextSpacing, .component, .spacing, .token(.spaceXXS), .length),
        NookDimensionToken(.activityCardVerticalPadding, .component, .spacing, .token(.spaceXXL), .length),
        NookDimensionToken(.activityCardHorizontalPadding, .component, .spacing, .token(.spaceMD), .length),
        NookDimensionToken(.volumeGlyphOpacity, .component, .none, .points(0.85), .opacity),
        NookDimensionToken(.placeholderStackSpacing, .component, .spacing, .token(.spaceLG), .length),
        NookDimensionToken(.placeholderMarkSize, .component, .none, .points(56), .length),
        NookDimensionToken(.placeholderMarkStrokeWidth, .component, .none, .points(2), .length),
        NookDimensionToken(.placeholderVerticalPadding, .component, .spacing, .points(40), .length),
        NookDimensionToken(.settingsSectionSpacing, .component, .spacing, .token(.spaceXXL), .length),
        NookDimensionToken(.settingsGroupSpacing, .component, .spacing, .token(.spaceXL), .length),
        NookDimensionToken(.settingsRowSpacing, .component, .spacing, .token(.spaceLG), .length),
        NookDimensionToken(.settingsBlockSpacing, .component, .spacing, .token(.spaceLG), .length),
        NookDimensionToken(.settingsFieldSpacing, .component, .spacing, .points(5), .length),
        NookDimensionToken(.settingsTextSpacing, .component, .spacing, .token(.spaceXXS), .length),
        NookDimensionToken(.settingsAboutTextSpacing, .component, .spacing, .points(3), .length),
        NookDimensionToken(.settingsInlineSpacing, .component, .spacing, .token(.spaceSM), .length),
        NookDimensionToken(.settingsContentBottomPadding, .component, .spacing, .points(14), .length),
        NookDimensionToken(.settingsRowVerticalPadding, .component, .spacing, .token(.spaceXS), .length),
        NookDimensionToken(.settingsIconWidth, .component, .none, .points(18), .length),
        NookDimensionToken(.settingsDisclosureGutter, .component, .none, .points(24), .length),
        NookDimensionToken(.settingsSectionLabelTracking, .component, .none, .points(0.42), .tracking),
        NookDimensionToken(.settingsConnectorWidth, .component, .none, .points(1), .length),
        NookDimensionToken(.settingsConnectorOpacity, .component, .none, .points(0.5), .opacity),
        NookDimensionToken(.settingsAccentSwatchSize, .component, .none, .points(18), .length),
        NookDimensionToken(.settingsAccentSwatchStrokeWidth, .component, .none, .points(1.5), .length),
        NookDimensionToken(.settingsAccentSwatchSelectedOpacity, .component, .none, .points(0.85), .opacity),
        NookDimensionToken(.shortcutKeyCapMinWidth, .component, .none, .points(24), .length),
        NookDimensionToken(.shortcutKeyCapMinHeight, .component, .none, .points(22), .length),
        NookDimensionToken(.shortcutKeyCapCornerRadius, .component, .radius, .token(.radiusSM), .length),
        NookDimensionToken(.shortcutKeyCapLabelOpacity, .component, .none, .points(0.92), .opacity),
        NookDimensionToken(.shortcutKeyCapFillOpacity, .component, .none, .points(0.55), .opacity),
        NookDimensionToken(.shortcutKeyCapStrokeOpacity, .component, .none, .points(0.35), .opacity),
        NookDimensionToken(.shortcutKeyCapStrokeWidth, .component, .none, .points(1), .length),
        NookDimensionToken(.shortcutKeyCapSpacing, .component, .spacing, .token(.spaceXS), .length),
        NookDimensionToken(.settingsRecordingHorizontalPadding, .component, .spacing, .token(.spaceLG), .length),
        NookDimensionToken(.settingsRecordingMinHeight, .component, .none, .points(22), .length),
        NookDimensionToken(.settingsRecordingFillOpacity, .component, .none, .points(0.7), .opacity),
        NookDimensionToken(.settingsRecordingStrokeOpacity, .component, .none, .points(0.6), .opacity),
        NookDimensionToken(.settingsRecordingStrokeWidth, .component, .none, .points(1), .length),
        NookDimensionToken(.settingsTitleEmphasisOpacity, .component, .none, .points(0.95), .opacity),
        NookDimensionToken(.settingsRecordingLabelOpacity, .component, .none, .points(0.9), .opacity),
        NookDimensionToken(.settingsFailureRowSpacing, .component, .spacing, .token(.spaceXS), .length),
    ]

    /// The chrome fonts, in `NookChromeTypography` declaration order.
    static let typographyTokens: [NookFontToken] = [
        NookFontToken(.headerIcon, .component, NookFontSpec(role: .typeGlyph)),
        NookFontToken(.topBarLabel, .component, NookFontSpec(role: .typeBody)),
        NookFontToken(.breadcrumbChevron, .component, NookFontSpec(size: .token(.typeSize2XS), weight: .bold)),
        NookFontToken(.switcherChevron, .component, NookFontSpec(size: .points(7), weight: .semibold)),
        NookFontToken(.compactLeadingGlyph, .component, NookFontSpec(size: .token(.typeSizeSM), weight: .semibold)),
        NookFontToken(.bannerSeverityGlyph, .component, NookFontSpec(role: .typeGlyph)),
        NookFontToken(.bannerMessage, .component, NookFontSpec(size: .points(10.5), weight: .medium)),
        NookFontToken(.bannerDismissGlyph, .component, NookFontSpec(size: .token(.typeSizeXS), weight: .bold)),
        NookFontToken(.shelfDropZoneIcon, .component, NookFontSpec(size: .token(.typeSizeDisplay), weight: .light)),
        NookFontToken(.shelfCaption, .component, NookFontSpec(size: .token(.typeSizeMD))),
        NookFontToken(.shelfHeaderLabel, .component, NookFontSpec(role: .typeLabel)),
        NookFontToken(.shelfChipLabel, .component, NookFontSpec(size: .token(.typeSizeSM), weight: .medium)),
        NookFontToken(.shelfFallbackGlyph, .component, NookFontSpec(size: .points(30), weight: .light)),
        NookFontToken(.shelfRemoveGlyph, .component, NookFontSpec(size: .token(.typeSizeXL))),
        NookFontToken(.activityIcon, .component, NookFontSpec(size: .token(.typeSizeDisplay), weight: .medium)),
        NookFontToken(.activityTitle, .component, NookFontSpec(size: .token(.typeSizeXL), weight: .semibold)),
        NookFontToken(.activitySubtitle, .component, NookFontSpec(size: .token(.typeSizeMD))),
        NookFontToken(.volumeGlyph, .component, NookFontSpec(role: .typeGlyph)),
        NookFontToken(.placeholderTitle, .component, NookFontSpec(size: .token(.typeSize2XL), weight: .medium)),
        NookFontToken(.placeholderBody, .component, NookFontSpec(role: .typeBody)),
        NookFontToken(.settingsSectionLabel, .component, NookFontSpec(size: .token(.typeSizeXS), weight: .semibold)),
        NookFontToken(.settingsHint, .component, NookFontSpec(size: .token(.typeSizeXS), weight: .regular)),
        NookFontToken(.settingsCaption, .component, NookFontSpec(role: .typeCaption)),
        NookFontToken(.settingsVersionLabel, .component, NookFontSpec(role: .typeCaption, design: .monospaced)),
        NookFontToken(.settingsFieldLabel, .component, NookFontSpec(size: .token(.typeSizeSM), weight: .medium)),
        NookFontToken(.settingsCommandChevron, .component, NookFontSpec(size: .token(.typeSizeSM), weight: .bold)),
        NookFontToken(.settingsRowDetail, .component, NookFontSpec(role: .typeBody)),
        NookFontToken(.settingsRowTitle, .component, NookFontSpec(role: .typeLabel)),
        NookFontToken(.settingsEmphasis, .component, NookFontSpec(role: .typeGlyph)),
        NookFontToken(.settingsCommandTitle, .component, NookFontSpec(size: .token(.typeSizeLG), weight: .regular)),
        NookFontToken(.settingsCommandIcon, .component, NookFontSpec(size: .token(.typeSizeLG), weight: .semibold)),
        NookFontToken(.settingsDisclosureChevron, .component, NookFontSpec(size: .token(.typeSize2XS), weight: .bold)),
    ]
}

extension NookResolvedTokens {
    /// Each `NookChromeMetrics` field and the token that sets it, in declaration order.
    static var metricFields: [(id: NookDimensionID, keyPath: WritableKeyPath<NookChromeMetrics, CGFloat>)] {
        [
            (.edgePadding, \.edgePadding),
            (.expandedColumnSpacing, \.expandedColumnSpacing),
            (.topBarHeight, \.topBarHeight),
            (.topBarItemSpacing, \.topBarItemSpacing),
            (.leadingClusterSpacing, \.leadingClusterSpacing),
            (.trailingClusterSpacing, \.trailingClusterSpacing),
            (.breadcrumbMaxWidth, \.breadcrumbMaxWidth),
            (.headerIconSize, \.headerIconSize),
            (.headerIconCornerRadius, \.headerIconCornerRadius),
            (.headerIconStrokeWidth, \.headerIconStrokeWidth),
            (.headerIconHoverLabelOpacity, \.headerIconHoverLabelOpacity),
            (.brandMarkSize, \.brandMarkSize),
            (.brandMarkStrokeWidth, \.brandMarkStrokeWidth),
            (.brandMarkOpacity, \.brandMarkOpacity),
            (.compactSlotSize, \.compactSlotSize),
            (.compactLeadingGlyphOpacity, \.compactLeadingGlyphOpacity),
            (.compactTrailingMarkSize, \.compactTrailingMarkSize),
            (.compactTrailingMarkStrokeWidth, \.compactTrailingMarkStrokeWidth),
            (.compactTrailingMarkOpacity, \.compactTrailingMarkOpacity),
            (.bannerRowSpacing, \.bannerRowSpacing),
            (.bannerCornerRadius, \.bannerCornerRadius),
            (.bannerContentHorizontalPadding, \.bannerContentHorizontalPadding),
            (.bannerContentVerticalPadding, \.bannerContentVerticalPadding),
            (.bannerSeverityGlyphTopInset, \.bannerSeverityGlyphTopInset),
            (.bannerDismissButtonSize, \.bannerDismissButtonSize),
            (.bannerMessageLabelOpacity, \.bannerMessageLabelOpacity),
            (.bannerStrokeOpacity, \.bannerStrokeOpacity),
            (.bannerStrokeWidth, \.bannerStrokeWidth),
            (.shelfContentSpacing, \.shelfContentSpacing),
            (.shelfRootVerticalPadding, \.shelfRootVerticalPadding),
            (.shelfDropZoneVerticalPadding, \.shelfDropZoneVerticalPadding),
            (.shelfDropZoneCornerRadius, \.shelfDropZoneCornerRadius),
            (.shelfDropZoneStrokeWidth, \.shelfDropZoneStrokeWidth),
            (.shelfHeaderSpacing, \.shelfHeaderSpacing),
            (.shelfChipSpacing, \.shelfChipSpacing),
            (.shelfChipWidth, \.shelfChipWidth),
            (.shelfChipPadding, \.shelfChipPadding),
            (.shelfChipCornerRadius, \.shelfChipCornerRadius),
            (.shelfIconSize, \.shelfIconSize),
            (.shelfRowVerticalPadding, \.shelfRowVerticalPadding),
            (.activityCardSpacing, \.activityCardSpacing),
            (.activityIconWidth, \.activityIconWidth),
            (.activityTextSpacing, \.activityTextSpacing),
            (.activityCardVerticalPadding, \.activityCardVerticalPadding),
            (.activityCardHorizontalPadding, \.activityCardHorizontalPadding),
            (.volumeGlyphOpacity, \.volumeGlyphOpacity),
            (.placeholderStackSpacing, \.placeholderStackSpacing),
            (.placeholderMarkSize, \.placeholderMarkSize),
            (.placeholderMarkStrokeWidth, \.placeholderMarkStrokeWidth),
            (.placeholderVerticalPadding, \.placeholderVerticalPadding),
            (.settingsSectionSpacing, \.settingsSectionSpacing),
            (.settingsGroupSpacing, \.settingsGroupSpacing),
            (.settingsRowSpacing, \.settingsRowSpacing),
            (.settingsBlockSpacing, \.settingsBlockSpacing),
            (.settingsFieldSpacing, \.settingsFieldSpacing),
            (.settingsTextSpacing, \.settingsTextSpacing),
            (.settingsAboutTextSpacing, \.settingsAboutTextSpacing),
            (.settingsInlineSpacing, \.settingsInlineSpacing),
            (.settingsContentBottomPadding, \.settingsContentBottomPadding),
            (.settingsRowVerticalPadding, \.settingsRowVerticalPadding),
            (.settingsIconWidth, \.settingsIconWidth),
            (.settingsDisclosureGutter, \.settingsDisclosureGutter),
            (.settingsSectionLabelTracking, \.settingsSectionLabelTracking),
            (.settingsConnectorWidth, \.settingsConnectorWidth),
            (.settingsConnectorOpacity, \.settingsConnectorOpacity),
            (.settingsAccentSwatchSize, \.settingsAccentSwatchSize),
            (.settingsAccentSwatchStrokeWidth, \.settingsAccentSwatchStrokeWidth),
            (.settingsAccentSwatchSelectedOpacity, \.settingsAccentSwatchSelectedOpacity),
            (.shortcutKeyCapMinWidth, \.shortcutKeyCapMinWidth),
            (.shortcutKeyCapMinHeight, \.shortcutKeyCapMinHeight),
            (.shortcutKeyCapCornerRadius, \.shortcutKeyCapCornerRadius),
            (.shortcutKeyCapLabelOpacity, \.shortcutKeyCapLabelOpacity),
            (.shortcutKeyCapFillOpacity, \.shortcutKeyCapFillOpacity),
            (.shortcutKeyCapStrokeOpacity, \.shortcutKeyCapStrokeOpacity),
            (.shortcutKeyCapStrokeWidth, \.shortcutKeyCapStrokeWidth),
            (.shortcutKeyCapSpacing, \.shortcutKeyCapSpacing),
            (.settingsRecordingHorizontalPadding, \.settingsRecordingHorizontalPadding),
            (.settingsRecordingMinHeight, \.settingsRecordingMinHeight),
            (.settingsRecordingFillOpacity, \.settingsRecordingFillOpacity),
            (.settingsRecordingStrokeOpacity, \.settingsRecordingStrokeOpacity),
            (.settingsRecordingStrokeWidth, \.settingsRecordingStrokeWidth),
            (.settingsTitleEmphasisOpacity, \.settingsTitleEmphasisOpacity),
            (.settingsRecordingLabelOpacity, \.settingsRecordingLabelOpacity),
            (.settingsFailureRowSpacing, \.settingsFailureRowSpacing),
        ]
    }

    /// Each `NookChromeTypography` field and the token that sets it, in declaration order.
    static var typographyFields: [(id: NookFontID, keyPath: WritableKeyPath<NookChromeTypography, Font>)] {
        [
            (.headerIcon, \.headerIcon),
            (.topBarLabel, \.topBarLabel),
            (.breadcrumbChevron, \.breadcrumbChevron),
            (.switcherChevron, \.switcherChevron),
            (.compactLeadingGlyph, \.compactLeadingGlyph),
            (.bannerSeverityGlyph, \.bannerSeverityGlyph),
            (.bannerMessage, \.bannerMessage),
            (.bannerDismissGlyph, \.bannerDismissGlyph),
            (.shelfDropZoneIcon, \.shelfDropZoneIcon),
            (.shelfCaption, \.shelfCaption),
            (.shelfHeaderLabel, \.shelfHeaderLabel),
            (.shelfChipLabel, \.shelfChipLabel),
            (.shelfFallbackGlyph, \.shelfFallbackGlyph),
            (.shelfRemoveGlyph, \.shelfRemoveGlyph),
            (.activityIcon, \.activityIcon),
            (.activityTitle, \.activityTitle),
            (.activitySubtitle, \.activitySubtitle),
            (.volumeGlyph, \.volumeGlyph),
            (.placeholderTitle, \.placeholderTitle),
            (.placeholderBody, \.placeholderBody),
            (.settingsSectionLabel, \.settingsSectionLabel),
            (.settingsHint, \.settingsHint),
            (.settingsCaption, \.settingsCaption),
            (.settingsVersionLabel, \.settingsVersionLabel),
            (.settingsFieldLabel, \.settingsFieldLabel),
            (.settingsCommandChevron, \.settingsCommandChevron),
            (.settingsRowDetail, \.settingsRowDetail),
            (.settingsRowTitle, \.settingsRowTitle),
            (.settingsEmphasis, \.settingsEmphasis),
            (.settingsCommandTitle, \.settingsCommandTitle),
            (.settingsCommandIcon, \.settingsCommandIcon),
            (.settingsDisclosureChevron, \.settingsDisclosureChevron),
        ]
    }

    /// Each `NookChromeMotion` field and the token that sets it, in declaration order.
    static var motionFields: [(id: NookAnimationID, keyPath: WritableKeyPath<NookChromeMotion, Animation>)] {
        [
            (.viewModeChange, \.viewModeChange),
            (.leadingClusterBack, \.leadingClusterBack),
            (.leadingClusterHover, \.leadingClusterHover),
            (.statusBanner, \.statusBanner),
            (.breadcrumb, \.breadcrumb),
            (.settingsDisclosure, \.settingsDisclosure),
            (.moduleSwitch, \.moduleSwitch),
            (.activityCard, \.activityCard),
        ]
    }
}
